<?php

/**
 * Magento
 *
 * @category   Payir
 * @package    Payir
 * @copyright  Copyright (c) 2017 Pay.ir (https://pay.ir/)
 */

echo $this->getMethod()->getTitle() . '<br/>';

if ($this->getInfo()->getLastTransId() == '') {
	echo '<em>' . $this->__('You will be redirected to Pay.ir website when you place an order.') . '</em>';
}
else {
	echo $this->__('Pay.ir Transaction ID: %s', $this->htmlEscape($this->getInfo()->getLastTransId())) . '<br/>';
}
