<?php

/**
 * Magento
 *
 * @category   Payir
 * @package    Payir
 * @copyright  Copyright (c) 2017 Pay.ir (https://pay.ir/)
 */
?>

<html>
<meta http-equiv="refresh" content="0; URL=<?php echo $this->getSuccessUrl() ?>">
<body>
<p><?php echo $this->__('Your payment has been successfully processed by our shop system.') ?></p>
<p><?php echo $this->__('Please click <a href="%s">here</a> if you are not redirected automatically.', $this->getSuccessUrl()) ?></p>
</body>
</html>
